Controllers/PizzasController.cs
using Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;

namespace la_mia_pizzeria_crud_mvc.Controllers
{
    [Authorize]
    public class PizzasController : Controller
    {

        PizzaContext db;

        //Codice eseguito prima di tutto
        public PizzasController()
        {
            db = new();

            //Inserisco queste righe di codice per poter inserire i decimali nell'input type="Number" dell'HTML poichè nel formato americano vi sono i punti e nell'italiano le virgole.
            System.Globalization.CultureInfo customCulture = (System.Globalization.CultureInfo)System.Threading.Thread.CurrentThread.CurrentCulture.Clone();
            customCulture.NumberFormat.NumberDecimalSeparator = ".";

            System.Threading.Thread.CurrentThread.CurrentCulture = customCulture;

            //Aggiungo nel DB pizze, categorie ed ingredienti se non esistono
            StaticPush();
        }

        public IActionResult Index() { return View(db.Pizzas.ToList()); }

        public IActionResult Show(int id)
        {
            Pizza pizza = db.Pizzas.Where(pizzas => pizzas.PizzaId == id).Include("Category").Include("Ingredients").FirstOrDefault();

            if (pizza == null)
            {
                return NotFound($"La pizza con id {id} non è stata trovata");
            }
            else
            {
                return View(pizza);
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            PizzaWithCategory pizzaWithCategory = new()
            {
                Categories = db.Categories.ToList(),
                Ingredients = db.Ingredients.ToList()
            };

            return View(pizzaWithCategory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Store(PizzaWithCategory model)
        {

            if (!ModelState.IsValid)
            {
                model.Categories = db.Categories.ToList();
                model.Ingredients = db.Ingredients.ToList();
                return View("Create", model);
            }

            model.Pizza.Ingredients = db.Ingredients.Where(ingredient => model.SelectedIngredients.Contains(ingredient.IngredientId)).ToList<Ingredient>();

            db.Add(model.Pizza);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Pizza pizza = db.Pizzas.Include("Category").Include("Ingredients").Where(pizza => pizza.PizzaId == id).FirstOrDefault();

            if (pizza == null)
            {
                return NotFound("Non è stato possibile trovare la pizza da modificare");
            }
            else
            {
                PizzaWithCategory pizzaWithCategory = new()
                {
                    Pizza = pizza,
                    Categories = db.Categories.ToList(),
                    Ingredients = db.Ingredients.ToList()
                };

                foreach (Ingredient ingredient in pizza.Ingredients)
                {
                    pizzaWithCategory.SelectedIngredients.Add(ingredient.IngredientId);
                }

                return View(pizzaWithCategory);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, PizzaWithCategory model)
        {

            if (!ModelState.IsValid)
            {
                model.Categories = db.Categories.ToList();
                model.Ingredients = db.Ingredients.ToList();
                model.Pizza.PizzaId = id;
                return View("Edit", model);
            }

            Pizza pizza = db.Pizzas.Include("Category").Include("Ingredients").Where(pizza => pizza.PizzaId == id).First();

            pizza.Name = model.Pizza.Name;
            pizza.Description = model.Pizza.Description;
            pizza.Image = model.Pizza.Image;
            pizza.Price = model.Pizza.Price;
            pizza.CategoryId = model.Pizza.CategoryId;

            pizza.Ingredients = db.Ingredients.Where(ingredient => model.SelectedIngredients.Contains(ingredient.IngredientId)).ToList();

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            Pizza pizza = db.Pizzas.Find(id);

            if (pizza == null)
            {
                return NotFound();
            }
            else
            {
                db.Pizzas.Remove(pizza);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

        }

        private void StaticPush()
        {
            //Se la tabella Categories del DB è vuota, aggiungo delle categorie d'esempio
            if (db.Categories.ToList().Count == 0)
            {
                db.Add(new Category("Pizza bianche"));
                db.Add(new Category("Pizza vegetariane"));
                db.Add(new Category("Pizza classiche"));
                db.Add(new Category("Pizza di mare"));
                db.SaveChanges();
            }

            //Se la tabella Ingredients del DB è vuota, aggiungo degli ingredienti d'esempio
            if (db.Ingredients.ToList().Count == 0)
            {
                db.Add(new Ingredient("Acciughe"));
                db.Add(new Ingredient("Pomodoro"));
                db.Add(new Ingredient("Wurstel"));
                db.Add(new Ingredient("Funghi"));
                db.Add(new Ingredient("Panna"));
                db.SaveChanges();
            }

            //Se la tabella Pizzas del DB è vuota, aggiungo delle pizze d'esempio
            if (db.Pizzas.ToList().Count == 0)
            {
                db.Add(new Pizza("Margherita", "La pizza Margherita", "https://primochef.it/wp-content/uploads/2019/08/SH_pizza_fatta_in_casa-1200x800.jpg", 10.50m, 1, new List<Ingredient>() { db.Ingredients.Find(2) }));
                db.Add(new Pizza("Napoli", "La pizza Napoli è buona", "https://media-cdn.tripadvisor.com/media/photo-s/18/03/98/d6/received-665664433902722.jpg", 14.50m, 2, new List<Ingredient>() { db.Ingredients.Find(2), db.Ingredients.Find(3) }));
                db.Add(new Pizza("Romana", "La pizza Romana è buona", "https://recipesblob.oetker.com/files/95bdfe7334364b41b557c734cd1c64c4/889e39b112414a9aa2b3ae5a9f787f6b/1272x764/pizza-alla-romanajpg.jpg", 17.50m, 3, new List<Ingredient>() { db.Ingredients.Find(4), db.Ingredients.Find(5) }));
                db.Add(new Pizza("4 Gusti", "La pizza 4 Gusti è buona", "https://media-cdn.tripadvisor.com/media/photo-s/07/61/12/f1/pizza-4-gusti.jpg", 5.50m, 4, new List<Ingredient>() { db.Ingredients.Find(1), db.Ingredients.Find(5) }));
                db.SaveChanges();
            }
        }

    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Pizzas" asp-action="Index">la-mia-pizzeria-crud-mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - la-mia-pizzeria-crud-mvc
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>